version: "3.6"
services:
  v_pi:
    image: php:${PHP_VERSION:-7.4.19-fpm}
    container_name: ${PROJECT_NAME}_v_pi
    volumes:
      - ./system/config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./system/config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./PUBLIC:/var/www/html
    environment:
      - V_PI_DB_NAME=${V_PI_DB_NAME:-v_pi_db}
      - V_PI_TABLE_PREFIX=${V_PI_TABLE_PREFIX:-v_pi_}
      - V_PI_DB_HOST=${V_PI_DB_HOST:-mysql}
      - V_PI_DB_USER=${V_PI_DB_USER:-root}
      - V_PI_DB_PASSWORD=${V_PI_DB_PASSWORD:-password}
  #  mem_limit: 1024m
  #  mem_reservation: 512M
  #  cpus: 8
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${PROJECT_NAME}_mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./system/backup:/backup
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-v_pi_db}
      - UPLOAD_LIMIT=300M
      - MAX_EXECUTION_TIME=9000
      - MEMORY_LIMIT=2048
      - PMA_CONTROLUSER=V_XOm
      - PMA_CONTROLPASS=V_XOm
    restart: always
    ports:
      - 6000:${MYSQL_PORT}

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${PROJECT_NAME}_nginx
  #  mem_limit: 1536m
  #  mem_reservation: 256M
  #  cpus: 2
    ports:
      - 4040:80
      - 443:443
    volumes:
      - ${NGINX_CONF_DIR:-./system/config/nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./system/logs/nginx}:/var/log/nginx
      - ${V_PI_DATA_DIR:-./PUBLIC}:/var/www/html
      - ${SSL_CERTS_DIR:-./system/certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./system/certs-data}:/data/letsencrypt
    depends_on:
      - v_pi
    restart: always

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${PROJECT_NAME}_mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 450M
    links:
      - mysql

#  mysql-cron-backup:
#    container_name: ${PROJECT_NAME}_bckup
#    image: fradelg/mysql-cron-backup
#    depends_on:
#      - mysql
#    restart: unless-stopped
#    volumes:
#      - ./system/backup:/backup
#    environment:
#      - MYSQL_USER=${MYSQL_USER:-root}
#      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD:-password}
#      - CRON_TIME=0 0 * * *
#      - MYSQL_NAME=${PROJECT_NAME}_mysql
#      - MYSQL_PORT=${MYSQL_PORT}
#      - TIMEOUT=300s
#      - INIT_BACKUP=0
#      - MAX_BACKUPS=10
#      - GZIP_LEVEL=5
